const char HTML[] PROGMEM ="<!DOCTYPE html>\n"
"<html>\n"
"  <head>\n"
"    <title>DoggyLights🐶🌈</title>\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" >\n"
"    <style>\n"
"      body {\n"
"      font-family: Trebuchet MS; \n"
"      color: #E7E8EB; \n"
"      background-color: #1B1B1B;}\n"
"      /* Style the tab */\n"
"      .tab {\n"
"      overflow: hidden;\n"
"      border: 1px solid #eee;\n"
"      color: #363636;\n"
"      background-color: #121212;\n"
"      }\n"
"      /* Style the buttons inside the tab */\n"
"      .tab button {\n"
"      background-color: inherit;\n"
"      color: #eee; \n"
"      float: left;\n"
"      border: none;\n"
"      outline: none;\n"
"      cursor: pointer;\n"
"      width: 50%;\n"
"      padding: 14px;\n"
"      transition: 0.3s;\n"
"      font-size: 17px;\n"
"      }\n"
"      /* Change background color of buttons on hover */\n"
"      .tab button:hover {\n"
"      background-color: #3d3d3d;\n"
"      color: #eee; \n"
"      }\n"
"      /* Create an active/current tablink class */\n"
"      .tab button.active {\n"
"      background-color: #282828;\n"
"      color: #eee; \n"
"      }\n"
"      /* Style the tab content */\n"
"      .tabcontent {\n"
"      display: none;\n"
"      padding: 6px 12px;\n"
"      border: 1px solid #ccc;\n"
"      border-top: none;\n"
"      }\n"
"      .spectrum {\n"
"      display: block;\n"
"      width: 200px;\n"
"      height: 30px;\n"
"      margin: 0 0 -3px 7px;\n"
"      background: -webkit-linear-gradient(left, hsl(0, 100%, 50%), hsl(60, 100%, 50%), hsl(120, 100%, 50%), hsl(180, 100%, 50%), hsl(240, 100%, 50%), hsl(300, 100%, 50%), hsl(360, 100%, 50%)  100%);\n"
"      }\n"
"      input[type=range] {\n"
"      width: 210px;\n"
"      margin-top: -5px;\n"
"      }\n"
"    </style>\n"
"  </head>\n"
"  <body>\n"
"    <h2>Dog light configurator</h2>\n"
"    <div class=\"tab\">\n"
"      <button class=\"tablinks\" onclick=\"openTab(event, 'Lights')\" id=\"defaultOpen\">Lights</button>\n"
"      <button class=\"tablinks\" onclick=\"openTab(event, 'Device')\">Device</button>\n"
"    </div>\n"
"    <div id=\"Lights\" class=\"tabcontent\">\n"
"      <p>Configure your lights.</p>\n"
"      <canvas id=\"myCanvas\" width=\"250\" height=\"150\" ></canvas>\n"
"      <form action=\"/get\">\n"
"        <br>\n"
"        <p>LED 1 Color:</p>\n"
"        <span class=\"spectrum\"></span>\n"
"        <input id=\"colorInput1\" type=\"range\" min=\"0\" max=\"360\" step=\"1\" onpointerup=myFunc()>\n"
"        <br>\n"
"        <p>LED 2 Color:</p>\n"
"        <span class=\"spectrum\"></span>\n"
"        <input id=\"colorInput2\" type=\"range\" min=\"0\" max=\"360\" step=\"1\" onpointerup=myFunc()>\n"
"        <br>\n"
"        <input type=\"submit\" value=\"Save\">\n"
"      </form>\n"
"      <script>\n"
"        const a = document.getElementById(\"myCanvas\");\n"
"        const atx = a.getContext(\"2d\");\n"
"        \n"
"        atx.beginPath();\n"
"        atx.fillStyle = '#333';\n"
"        atx.fillRect(20, 20, 200, 100);  // Case\n"
"        atx.rect(20, 20, 200, 100);\n"
"        atx.stroke();\n"
"        \n"
"        atx.beginPath();\n"
"        atx.rect(40, 50, 40, 40);\n"
"        atx.fillStyle = 'hsl(180,100%, 50%)';\n"
"        atx.fillRect(40, 50, 40, 40);  // LED1\n"
"        atx.stroke();\n"
"        \n"
"        atx.beginPath();\n"
"        atx.rect(150, 50, 40, 40);\n"
"        atx.fillStyle = 'hsl(180,100%, 50%)';\n"
"        atx.fillRect(150, 50, 40, 40);  // LED2\n"
"        atx.stroke();\n"
"        \n"
"        function myFunc(){\n"
"        var color1 = document.getElementById(\"colorInput1\").value;\n"
"        var color2 = document.getElementById(\"colorInput2\").value;\n"
"        const c = document.getElementById(\"myCanvas\");\n"
"        const ctx = c.getContext(\"2d\");\n"
"        \n"
"        ctx.beginPath();\n"
"        ctx.fillStyle = 'hsl('+color1+',100%, 50%)';\n"
"        ctx.fillRect(40, 50, 40, 40);  // LED1\n"
"        ctx.stroke();\n"
"        \n"
"        ctx.beginPath();\n"
"        ctx.fillStyle = 'hsl('+color2+',100%, 50%)';\n"
"        ctx.fillRect(150, 50, 40, 40);  // LED2\n"
"        ctx.stroke();\n"
"        }\n"
"      </script> \n"
"    </div>\n"
"    <div id=\"Device\" class=\"tabcontent\">\n"
"      <p>Change the device name and password.</p>\n"
"      <form action=\"/get\">\n"
"        <label for=\"devicename\">Device name: </label>\n"
"        <input type=\"text\" name=\"devicename\"  placeholder = \"DoggyLights\" required>\n"
"        <br>\n"
"        <label for=\"password\">Password: </label>\n"
"        <input type=\"password\" name=\"password\"  required>\n"
"        <br>\n"
"        <input type=\"submit\" value=\"Save\">\n"
"      </form>\n"
"    </div>\n"
"    <script>\n"
"      console.log(document.getElementById(\"defaultOpen\").click());\n"
"      function openTab(evt, tabName) {\n"
"        var i, tabcontent, tablinks;\n"
"        tabcontent = document.getElementsByClassName(\"tabcontent\");\n"
"        for (i = 0; i < tabcontent.length; i++) {\n"
"          tabcontent[i].style.display = \"none\";\n"
"        }\n"
"        tablinks = document.getElementsByClassName(\"tablinks\");\n"
"        for (i = 0; i < tablinks.length; i++) {\n"
"          tablinks[i].className = tablinks[i].className.replace(\" active\", \"\");\n"
"        }\n"
"        document.getElementById(tabName).style.display = \"block\";\n"
"        evt.currentTarget.className += \" active\";\n"
"      }\n"
"    </script>\n"
"  </body>\n"
"</html>";

//const char HTML[] PROGMEM = "<!DOCTYPE html>\n<html>\n<head>\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<style>\nbody {font-family: Arial;}\n\n/* Style the tab */\n.tab {\n  overflow: hidden;\n  border: 1px solid #ccc;\n  background-color: #f1f1f1;\n}\n\n/* Style the buttons inside the tab */\n.tab button {\n  background-color: inherit;\n  float: left;\n  border: none;\n  outline: none;\n  cursor: pointer;\n  padding: 14px 16px;\n  transition: 0.3s;\n  font-size: 17px;\n}\n\n/* Change background color of buttons on hover */\n.tab button:hover {\n  background-color: #ddd;\n}\n\n/* Create an active/current tablink class */\n.tab button.active {\n  background-color: #ccc;\n}\n\n/* Style the tab content */\n.tabcontent {\n  display: none;\n  padding: 6px 12px;\n  border: 1px solid #ccc;\n  border-top: none;\n}\n</style>\n</head>\n<body>\n\n<h2>Doggy Lights</h2>\n\n<div class=\"tab\">\n  <button class=\"tablinks\" onclick=\"openCity(event, 'Lights')\">Lights</button>\n  <button class=\"tablinks\" onclick=\"openCity(event, 'Device')\">Device</button>\n</div>\n\n<div id=\"Lights\" class=\"tabcontent\">\n  <h3>Lights</h3>\n  <p>Change your light colors and animations!</p>\n</div>\n\n<div id=\"Device\" class=\"tabcontent\">\n  <h3>Device</h3>\n  <p>Rename your Doggy Lights!</p> \n</div>\n\n<script>\nfunction openCity(evt, cityName) {\n  var i, tabcontent, tablinks;\n  tabcontent = document.getElementsByClassName(\"tabcontent\");\n  for (i = 0; i < tabcontent.length; i++) {\n    tabcontent[i].style.display = \"none\";\n  }\n  tablinks = document.getElementsByClassName(\"tablinks\");\n  for (i = 0; i < tablinks.length; i++) {\n    tablinks[i].className = tablinks[i].className.replace(\" active\", \"\");\n  }\n  document.getElementById(cityName).style.display = \"block\";\n  evt.currentTarget.className += \" active\";\n}\n</script>\n   \n</body>\n</html> \n";
// ssid = preferences.getString("ssid", "");
//password = preferences.getString("password", "");
void handleWifi() {
  while (wifiRunning) {
    solidPulsing(1, 0, 1, 0, 1, 0, 15);
  }
}

void setupWifi() {
  WiFi.softAP(ssid, password);

  Serial.println();
  Serial.print("IP address: ");
  Serial.println(WiFi.softAPIP());

  if (!MDNS.begin("doglights")) {
    Serial.println("Error setting up MDNS responder!");
    while (1) {
      delay(10);
    }
  }

  server.on("/", HTTP_GET, [](AsyncWebServerRequest *request) {
    request->send(200, "text/html", HTML);
  });

  server.begin();
  MDNS.addService("http", "tcp", 80);
}